Repository B05-232/plug-standard, pull requests merged in 2023-11, with the labels that each got.

#11 Add canvas interface
  src/Plug/Canvas/Canvas.h
  src/Plug/Canvas/SelectionMask.h
Labels: documentation, enhancement

#10 Add graphics wrappers
  src/Plug/Color.h
  src/Plug/Graphics.h
  src/Plug/Graphics/PrimitiveType.h
  src/Plug/Graphics/RenderTarget.h
  src/Plug/Graphics/Texture.h
  src/Plug/Graphics/VertexArray.h
Labels: documentation, enhancement

#2 Widget specification & implementation
  src/Impl/Widget.cpp
  src/Impl/Widget.h
  src/Plug/Widget.h
Labels: documentation, enhancement

#13 Debug widget rendering
  src/Impl/Widget.cpp
  src/Impl/Widget.h
Labels: enhancement

#9 Add Plugin, Filter and Tool interfaces
  src/Plug/Filter.h
  src/Plug/Plugin.h
  src/Plug/Tool.h
  src/Plug/Tool/ColorPalette.h
  src/Plug/Tool/ControlState.h
  src/Plug/Tool/Tool.h
Labels: documentation, enhancement

#14 Fix all compilation errors and warnings
  src/Impl/LayoutBox/LayoutBox.cpp
  src/Impl/LayoutBox/LayoutBox.h
  src/Impl/Widget.cpp
  src/Impl/Widget.h
  src/Plug/Canvas.h
  src/Plug/Canvas/Canvas.h
  src/Plug/Canvas/SelectionMask.h
  src/Plug/Color.h
  src/Plug/Graphics.h
  src/Plug/Graphics/Texture.h
  src/Plug/Graphics/VertexArray.h
  src/Plug/LayoutBox.h
  src/Plug/Tool/Tool.h
  src/Plug/Widget.h
Labels: bug

#27 Add constructors for events
  src/Plug/Event/Event.h
  src/Plug/Graphics/Texture.h
  src/Plug/Graphics/VertexArray.h
Labels: api

#26 Make getNativeHandle() virtual
  src/Plug/Graphics/RenderTarget.h
Labels: api

#29 Render target context switching
  src/Plug/Graphics/RenderTarget.h
Labels: enhancement, api

#32 Implement TransformStack
  src/Impl/TransformStack.cpp
  src/Impl/TransformStack.h
Labels: enhancement

#34 Add missing constant definition
  src/Impl/TransformStack.h
Labels: bug

#35 Implement event converter
  src/Impl/EventManager/SfmlEventManager.cpp
  src/Impl/EventManager/SfmlEventManager.h
Labels: enhancement

#42 Add missing public modifier
  src/Plug/Tool/Tool.h
Labels: bug

#43 Fix unusable texture interface
  src/Plug/Graphics/Texture.h
Labels: bug

#44 Fix dtor
  src/Plug/Canvas/Canvas.h
  src/Plug/Canvas/SelectionMask.h
  src/Plug/LayoutBox.h
  src/Plug/Plugin.h
  src/Plug/Widget.h
Labels: bug

#45 Remove `Canvas::getNativeHandle`
  src/Plug/Canvas/Canvas.h
Labels: bug, api

#49 Fix coordinate translation in `Widget::draw()`
  src/Impl/Widget.cpp
Labels: bug

#50 Add more SFML utility functions
  src/Impl/Util/Sfml.cpp
  src/Impl/Util/Sfml.h
  src/Plug/Canvas/Canvas.h
  src/Plug/Canvas/SelectionMask.h
Labels: enhancement

#51 Add getter for pixels in Texture
  src/Plug/Graphics/Texture.h
Labels: enhancement, api

#55 Make ColorPalette methods virtual
  src/Plug/Tool/ColorPalette.h
Labels: bug, api
